### ISSUE TITLE
Allow console output from Q.run() to be turned off

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#100]
**Desciption**
When a Q.run() is executed the following output is printed.
```
Getting results from database

Total execution time: 9338 ms
```
At times this is useful, at others it is not.

If I am writing a Python script which is printing output it is interrupted by the messages printed by Q.run().

For example, the output from my program is interrupted as follows:
```
Case id:11LU013
Getting results from database

Total execution time: 1260 ms

Imaging type/format
Counter({'SM/DICOM': 5})
________________________________________________________________________________
Case id:11LU022
Getting results from database

Total execution time: 1047 ms

Imaging type/format
Counter({'SM/DICOM': 5})
________________________________________________________________________________
Case id:11LU035
Getting results from database

Total execution time: 1295 ms

Imaging type/format
Counter({'SM/DICOM': 5})
```

The decision to print should be under control of the programmer using the API.

**Describe the solution you'd like**
- The ability to pass a 'verbose' parameter to run() that controls whether the print is performed or not.
- Default for verbose should be false.
- Execution time should be available as part of the value returned by Q.run()

**Alternatives**
The above provides for the alternative behaviors likely to be required.

Async queries would require different behavior.

**Comment by elijahlowe** [comment]
copied to jira

**Comment by ACharbonneau** [comment]
In version 3.0 please use the pagination function to return all of the results for a query.
