### ISSUE TITLE
Subjects are duplicated in results from query on Specimen.File where File is associated with more than one specimen

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#106]
**Description**
Where a file is associated with more than one specimen for the same Subject, queries on ResearchSubject.Specimen.File return the Subject multiple times, instead of once. This occurs in part where File is denormalized to other specimens - and that is how the problem was originally identified.

However, there are cases where the same file may show up genuinely within the same Subject.

**To Reproduce**
See notebook [Query by PDC filename](https://github.com/ianfore/cdatest/blob/main/v2tests/Query%20by%20PDC%20filename.ipynb)

**Expected behavior**
Each Subject and its contents should be returned only once.

**Comment by ACharbonneau** [comment]
Using the new 3.0 release endpoints, if you wanted results to be returned by Subject, you would search from the Subject endpoint rather than the Specimen one. Specimen will always return by specimen, not by subject.
