### ISSUE TITLE
Query 1 associated_project does not exist

### ISSUE THREAD

**Issue by rudnickp** [CancerDataAggregator/cda-python#109]
**Describe the bug**
Query of ResearchSubject.associated project gives the following error:

ERROR:root:
                Http Status: 500
                Error Message: Field name associated_project does not exist in STRUCT<id STRING, identifier ARRAY<STRUCT<system STRING, value STRING>>, member_of_research_project STRING, ...> at [1:234]

**To Reproduce**
1.Run ln 8 in the notebook

**Expected behavior**
Results of compound query.

**Desktop (please complete the following information):**
Windows
Chrome

**Comment by ACharbonneau** [comment]
This field is obsolete. Please use 'ResearchSubject.member_of_research_project'
