### ISSUE TITLE
Better support for iteration on queries

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-python#11]
The `Result` object has a `next_page()` method but no way to tell if more pages exist. If a user calls `next_page()` but there aren't any more, an exception is raised. Adding a method that returns a boolean value, such as `has_next_page()`, would be one way to fix this.

**Comment by YeastCell** [comment]
Hey @pshapiro4broad, I have a question that is not quite related to this, but I'll dump it here anyways:
Is there a way to get the total number of records in the result w/o iterating through all pages? I.e. `Count: <total_number>`. 
This is one of the very few features that is part of the console experience that I lack in the API.

**Comment by pshapiro4broad** [comment]
The feature request to get total rows is https://github.com/CancerDataAggregator/cda-service/issues/14

I think it will make sense to change cda-service to use bigquery pagination, which will make this easier to implement. The downside is that users won't be able to use `offset` anymore; instead they'll have to use `next` only.

**Comment by YeastCell** [comment]
Thanks, this is great! I wasn't going through the issues first.
