### ISSUE TITLE
Query 4 primary_disease_type does not exist

### ISSUE THREAD

**Issue by rudnickp** [CancerDataAggregator/cda-python#110]
**Describe the bug**
ERROR:root:
            Http Status: 500
            Error Message: Field name primary_disease_type does not exist in STRUCT<id STRING, identifier ARRAY<STRUCT<system STRING, value STRING>>, member_of_research_project STRING, ...> at [1:34]

**To Reproduce**
1. In the example notebook, Query 4 fails

**Comment by ACharbonneau** [comment]
You must specify the full name, i.e. 'ResearchSubject.Specimen.primary_disease_type' 

the notebook is updated
