### ISSUE TITLE
Provide documentation for comparators

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#13]
The README.md provides a beginning description of query formats (Quick and Detailed).

Can coverage of the legal comparators be provided, or a link to where that exists?

In the absence of looking for documentation I tried one guess at something I speculated might be legal and got the following

`ValueError: Invalid value for `node_type` (in), must be one of ['column', 'quoted', 'unquoted', '>=', '<=', '<', '>', '=', '~', 'AND', 'OR', 'NOT', 'SUBQUERY']`

At which point one remembers that Read The Manual is 'best practice', which leads to the request for documentation.

(Note this raises the question whether this is one manifestation of a #BigIssue - the more fundamental one of 'query language' )

**Comment by pshapiro4broad** [comment]
This is a good point, the documentation for cda-python should definitely have this information. Currently it's in the swagger docs, but even there you'd have to know where to look. If you open the swagger page (https://cda.cda-dev.broadinstitute.org/api/swagger-ui.html) and expand `Query` at the bottom of the page, you can see a description of the different node types. The complete list of accepted `node_type` values is visible by expanding the Enum array under `node_type`.

**Comment by elijahlowe** [comment]
closing, this is documented here: https://cda.readthedocs.io/en/latest/usage.html#q-comparison-operators
