### ISSUE TITLE
Avoid implementing a query language (#BigIssue)

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#15]
#BigIssue
Noting Alex's statement in Slack 

> I don’t want to do is get to a point that requests to our query APIs expand to things like “can i do where statements that select data from other tables”, etc and we effectively implement our own query language.  To me, I like the idea of an API layer being focused on a faceted sort of search methodology - let me do some boolean operations and filtering on a well defined set of fields.  If those APIs can return either the results or the SQL it generated, users who want more power can use that SQL template to further refine things.

Examples explored here (see #13 and #14) begin to identify that the expressivity of a full query language is necessary for even queries which, from a domain/scientific perspective, are quite basic. Creating issue here to give visibility to this question, linked to specific examples.

**Comment by DavidPotCanuck** [comment]
We are working towards implementing granularity on what can be searched and what can be returned in future releases.  Not implemented in Release 2.  Thank you for the feedback.

**Comment by ianfore** [comment]
In addition to the granularity question the MIDRC notebook (to be committed shortly) highlights another example where it is easier to do something via SQL than via a Q query. Mainly because SQL has the count function. It is conceivable how to do it in Python on the returned json from a Q query but the above option is simpler. 

A count function could be implemented in Q. It would also need some equivalent of group by. This comes back to Alex's instinct to avoid implementing a query language when there are good xQL's which provide this functionality and have a wide user base that knows how to use them, plus supporting toolsets.

**Comment by ndbolliger** [comment]
@ianfore, thanks for your feedback.  We have implemented a production release where you are a beta-tester.  Please give us your feedback on that.
