### ISSUE TITLE
SQL Query generated by cdapython causes duplication at top level

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#16]
The duplication problem is as seen in https://github.com/ianfore/cdatest/blob/main/09CO022%20Example.ipynb

The SQL generated in response to `Q('ResearchSubject.id = "c5421e34-e5c7-4ba5-aed9-146a5575fd8d"')` is 
`SELECT * FROM gdc-bq-sample.cda_mvp.v3, UNNEST(ResearchSubject) AS _ResearchSubject WHERE (_ResearchSubject.id = 'c5421e34-e5c7-4ba5-aed9-146a5575fd8d'`
See the notebook above for full details of the duplication

Exploration in the [SQL Exploration notebook](https://github.com/ianfore/cdatest/blob/main/SQL%20Exploration.ipynb) shows a modified version of this query yields the results that were probably intended. This avoids some of the duplication.

`SELECT p.* FROM gdc-bq-sample.cda_mvp.v3 p , 
UNNEST(ResearchSubject) AS _ResearchSubject 
WHERE (_ResearchSubject.id = 'c5421e34-e5c7-4ba5-aed9-146a5575fd8d')`

The key is to qualify the 'select *'  as referring to the root table which is essentially patient. Without this qualification of the nested columns from the nested subtables are also included in the result. Those nested structures are included anyway by the 'select p.*'.

Some duplication is still present e.g. the repetition of identical ResearchSubject details for the nested PDC and GDC Research Subjects. The correct model is that these details such as diagnosis should belong at a higher level in the tree. 

Some of the problem is likely also generated in how cda-client.py parse the results from BigQuery. For example, the root level id (which should be patient id) ends up holding the subject id in what is returned by cda-client.py. While the fix to the SQL above eliminates the duplication problem - there may be other issues arising from how cda-client.py turns the BigQuery results into Python objects and json.

**Comment by pshapiro4broad** [comment]
Regarding the first comment, about the SQL duplicating the results at the top level, I've had a chance to look at this and I see what you're saying; the `*` will select results from all the `FROM` sources, and we only want to select results from the first source, the table. I think your fix makes sense, and I'll address it in the cda-service layer in https://github.com/CancerDataAggregator/cda-service/issues/65

**Comment by pshapiro4broad** [comment]
I'm going to split the issues from the last two paragraphs into different tickets as they appear to be separate issues. Once the query that causes the duplication is fixed, we can re-run your examples and check and see if the other cases are addressed too.

**Comment by pshapiro4broad** [comment]
This is fixed with the CDA service release 0.1.12 https://github.com/CancerDataAggregator/cda-service/releases/tag/v0.0.12
