### ISSUE TITLE
Query results duplicate ResearchSubject details such as Diagnosis

### ISSUE THREAD

**Issue by pshapiro4broad** [CancerDataAggregator/cda-python#17]
Split from #16 :

Some duplication is still present e.g. the repetition of identical ResearchSubject details for the nested PDC and GDC Research Subjects. The correct model is that these details such as diagnosis should belong at a higher level in the tree.

Once #16 is resolved we can re-test and see if this problem is still present.

**Comment by pshapiro4broad** [comment]
This is a question about the way data in CDA is modeled, so I'll let someone else on the team respond to it. Looking at the results I get back, the contents of `Diagnosis` are identical except for `id`, not sure if this is important or not.

**Comment by ACharbonneau** [comment]
Duplication of results should be fixed in Release 3. Please open a new ticket in https://github.com/CancerDataAggregator/readthedocs/issues if you continue to see this problem
