### ISSUE TITLE
Provide new command for new user setup

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-python#19]
Provide the following command in the setup guide rather than the current `pip install` and to emphasize the requirements (python >= 3.6).
python3 -m pip install git+https://github.com/CancerDataAggregator/cda-python.git

**Comment by pshapiro4broad** [comment]
Note that a user may or may not have python 3 installed as `python3`. The instructions can list a few different steps that users can try. In general, if users aren't as familiar with python, they'd be better off using a notebook.

**Comment by elijahlowe** [comment]
see here: https://cda.readthedocs.io/en/latest/Installation.html#pip-install
