### ISSUE TITLE
Add examples of how to use UNNEST in CDA queries to documentation

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-python#21]

**Comment by pshapiro4broad** [comment]
I'm not sure about the need for this. If we can better support high level queries using the `boolean-query` API, we don't need to invest in better supporting users that want to use raw SQL queries. We don't want users to use BigQuery SQL in general, unless SQL is more comfortable for them than a higher level query API. If users are already comfortable with BQ SQL then they shouldn't need a tutorial on how to use `UNNEST`.

**Comment by fkaufman-asym** [comment]
Issue 21 fixed
