### ISSUE TITLE
Add example(s) of how to use ARRAY_AGG()

### ISSUE THREAD

**Issue by anniekuan** [CancerDataAggregator/cda-python#22]

**Comment by pshapiro4broad** [comment]
Google already provides detailed documentation for this function: https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg

Is there something specific to data the CDA provides that would make this function especially useful and worth mentioning in our documentation?

**Comment by fkaufman-asym** [comment]
We are closing this no action.
