### ISSUE TITLE
Q.sql allows anyone to search any public table ($$$)

### ISSUE THREAD

**Issue by elijahlowe** [CancerDataAggregator/cda-python#38]
Q.sql allows any user to use bigquery without having to use their on personal account, which can lead to CDA being charged for random bigquery usage if someone discovers this loophole.

Here is an example query (ncbi sra table):

r = Q.sql("""
select acc, biosample, bioproject, releasedate, librarylayout, mbases, organism 
FROM nih-sra-datastore.sra.metadata 
WHERE platform = "ILLUMINA" AND librarysource = "METAGENOMIC" AND consent = "public" AND assay_type = "WGS" AND libraryselection = "RANDOM"
""")

print(r[0])

#{'acc': 'SRR12933840', 'biosample': 'SAMN16557092', 'bioproject': 'PRJNA672125', 'releasedate': '1611187200.0', #'librarylayout': 'PAIRED', 'mbases': '627', 'organism': 'human gut metagenome'}

There should be a table whitelist where only relevant CDA tables can be searched.

**Comment by fkaufman-asym** [comment]
There is a soft fix to prevent anyone from searching anything other than gdc-bq-sample.

**Comment by ACharbonneau** [comment]
users cannot change the table in 3.0
