### ISSUE TITLE
Add table attribute to q.run method to give flexibility to run test tables.

### ISSUE THREAD

**Issue by fkaufman-asym** [CancerDataAggregator/cda-python#41]

**Comment by YeastCell** [comment]
Is this related to `table` and `version` arguments?
I was wondering if it's possible to add those arguments to `columns()` and `unique_terms()` functions as well?
There is no other way to test certain functionalities otherwise.

**Comment by fkaufman-asym** [comment]
This has been exercised and verified by the Testers
