### ISSUE TITLE
A pull of data from each node will populate the CDA release (snapshot on a given release)

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#49]
Because we are not doing versioning in this release, a pull from GDC, PDC and IDC will occur on a given date prior to the production release.  Those dates will be made public in our documentation,

**Comment by fkaufman-asym** [comment]
Donavan did this days before the release.

**Comment by elijahlowe** [comment]
closing see data release notes https://cda.readthedocs.io/en/latest/ReleaseNotes.html#datasets-fields
