### ISSUE TITLE
Some of our CDA entities will map to CCDH data model

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#53]
The CCDH data model continues to evolve.  CDA will be using some of that data model in this release.

This ticket describes the details of that naming, and what the associated fields in each node they map to.  This information will be placed in our documentation.

**Comment by kreinold** [comment]
**Release 2.0 will include the following (INT Release of 9/20 --Donovan's commit)** 

- Kathy to align fields that are missing in JSON with Donovan’s work
- Fields to be changed in 2.0 release
- Taxon => species -- and assume “Homo sapiens” for all GDC
- Add Subject field: subject_associated_project
- Add data_modality, imaging_modality to File
See [CDA_Schema_Feld_mapping for Release 2](https://docs.google.com/spreadsheets/d/1S4qxo_D-mKF_N7C-m8KV7Wbs-Nzeif_itpMrJwwEPOc/edit#gid=0)

**Release 2.1 will have significant focus on data modeling updates to align to the best of our ability with CRDC-H tag 1.0.1**
-

**Comment by kreinold** [comment]
Sorry, closed prematurely.

**Comment by DavidPotCanuck** [comment]
This is linked to the ticket:

https://github.com/CancerDataAggregator/transform/issues/78

@kreinold @druth314 please address issues in that ticket.

**Comment by elijahlowe** [comment]
closing related to epic #53
