### ISSUE TITLE
Q query functionality will be enhanced

### ISSUE THREAD

**Issue by DavidPotCanuck** [CancerDataAggregator/cda-python#55]
The functionality of Q query language will be enhanced.

These features will be added in release 2:

**Comment by dionboles-asym** [comment]
In issue #46 this is addressed

**Comment by anniekuan** [comment]
Also related to issue #14

**Comment by dionboles-asym** [comment]
I just renamed a function from single_operator_parser to query that is linked to this ticker #58

**Comment by elijahlowe** [comment]
closing ticket because part of epic #55
