### ISSUE TITLE
Use Collection Name for IDC Project Name in Transformation mapping 

### ISSUE THREAD

**Issue by kreinold** [CancerDataAggregator/cda-python#59]

**Comment by elijahlowe** [comment]
I'm not sure exactly what this means. How do I test this?

**Comment by druth314** [comment]
In the original IDC tables there is a field called collection_id that should map to the subject_associated_project for the idc table. I'd just compare a few files from IDC and see if the mapping matches up

**Comment by ACharbonneau** [comment]
I don't know what this means, but I assume it's done.
