### ISSUE TITLE
Updated unique terms table values

### ISSUE THREAD

**Issue by dionboles-asym** [CancerDataAggregator/cda-python#64]
This depends on a change in the cdaservice linked [here](https://github.com/CancerDataAggregator/cda-service/issues/103) but this adds a table parameter  and host parameter to the unique_terms. the parameters  are autofilled  to the .env values of DATABASETABLE and DATABASETABLE_VERSION  if the values not provided

**Comment by fkaufman-asym** [comment]
This has been implemented in both cda-service and cda-python
