### ISSUE TITLE
Adding files endpoint/flag logic

### ISSUE THREAD

**Issue by YeastCell** [CancerDataAggregator/cda-python#71]
cda-python code:

```
q1 = Q('File.identifier.system = ("GDC", "IDC")')
q2 = Q('sex = "female"')

q = q1.And(q2)
r = q.run(table='gdc-bq-sample.R2_practice_kit', version='all_v1', select='File')
```

SQL translation:

```
SELECT _File.id as id,
       ANY_VALUE(_File.identifier) as identifier,
       ANY_VALUE(_File.label) as label,
       ...
FROM `gdc-bq-sample.R2_practice_kit.all_v1` AS nodes,
UNNEST(File) AS _File,
UNNEST(identifier) AS _identifier
WHERE (
    nodes.id IN (
        SELECT nodes.id
        FROM `gdc-bq-sample.R2_practice_kit.all_v1` AS nodes,
        UNNEST(File) AS _File,
        UNNEST(identifier) AS _identifier
        WHERE _identifier.system = "GDC"
        GROUP BY nodes.id
        HAVING COUNT(*) >= 1
    )
    AND
    nodes.id IN (
        SELECT nodes.id
        FROM `gdc-bq-sample.R2_practice_kit.all_v1` AS nodes,
        UNNEST(File) AS _File,
        UNNEST(identifier) AS _identifier
        WHERE _identifier.system = "IDC"
        GROUP BY nodes.id
        HAVING COUNT(*) >= 1
    )
    AND
    _identifier.system IN ("GDC", "IDC")
    AND
    nodes.sex = "female"
)
GROUP BY _File.id
```

As we can see, there are two adjustments that happened on top of replaced `From` operator logic:
* The `SELECT` clause includes only File information
* There is additional condition in the `WHERE` clause that ensures we get only GDC and IDC files and that PDC files are excluded: `_identifier.system IN ("GDC", "IDC")`

SELECT clause that provides unique entries remains an open question (https://github.com/CancerDataAggregator/cda-service/issues/69). Although the solution outlined here will work, it may pose issues for scalability (i.e. when new fields are added). An alternative direction may include subqueries.

**Comment by ACharbonneau** [comment]
This should be fixed as of Release 3. You would now use the `in` method rather than `=`
