### ISSUE TITLE
cdapython query cannot be imported

### ISSUE THREAD

**Issue by pihltd** [CancerDataAggregator/cda-python#73]
The query feature from cdapython can't be imported:

`from cdapython import query`

causes this error message:
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_14768/391486788.py in <module>
----> 1 from cdapython import query

ImportError: cannot import name 'query' from 'cdapython' (/usr/local/lib/python3.8/dist-packages/cdapython.py)`

Q, columns and unique_terms import fine.  On Ubuntu 20.04, python 3.8, cdapython installed with pip 20.0.2 running in a local Jupyter lab 1.11.1.

**Comment by ACharbonneau** [comment]
query is being depreciated
