### ISSUE TITLE
Enhanced Logging in CDA-Service

### ISSUE THREAD

**Issue by fkaufman-asym** [CancerDataAggregator/cda-python#80]
Add JobId,  userEmail to output logging for enhanced performance and error tracking.

**Comment by fkaufman-asym** [comment]
Linked issue [https://github.com/CancerDataAggregator/cda-service/pull/121/]

**Comment by fkaufman-asym** [comment]
![image](https://user-images.githubusercontent.com/84089414/141532006-6b794bc3-94bf-47fe-b402-fabf6ba08cd6.png)

**Comment by elijahlowe** [comment]
closing see the screenshot from @fkaufman-asym
