### ISSUE TITLE
In Q, provide a count a count of subjects by node in results datatype

### ISSUE THREAD

**Issue by elijahlowe** [CancerDataAggregator/cda-python#83]
**Current output:**
		…
		Offset: 0
Count: 100
Total Row Count: 1628
More pages: True

**Proposed output:**
		…
		Offset: 0
		Total Count: 100
GDC Count: 100
PDC Count: 91
IDC Count: 76
Total Row Count: 1628
More pages: True

**Test case:**
```
q = Q('id = "TCGA-13-1409"')

r3 = q.run()

from collections import Counter
import pandas as pd

file_list = []
for patient in r3:
    #for ResearchSubject in patient['ResearchSubject']:
    for file in patient['File']:
        for identifier in file['identifier']:
            file_list.append(identifier)#['system'])
            #file_dcat.append(file['data_type'])
            
file_list = pd.DataFrame(file_list)
            
print("File: ", Counter(file_list['system']))

File:  Counter({'IDC': 191, 'PDC': 109, 'GDC': 54})
```
- GDC: v30.0, 09/27/2021
- PDC: v2.1, 09/27/2021
- IDC: v.4.0, 09/29/2021

**Open question:**
Should this count represent the number of subjects, files or both?

**Comment by ACharbonneau** [comment]
This has been implemented, but better, in 3.0
