### ISSUE TITLE
Queries should not be case sensitive

### ISSUE THREAD

**Issue by elijahlowe** [CancerDataAggregator/cda-python#86]
**Is your feature request related to a problem? Please describe.**
Case sensitivity should not affect the query. "Lung" and "lung" should be the same.

**Describe the solution you'd like**
No matter what case I enter, the results I'm looking for should be returned. 

**Describe alternatives you've considered**
There is no alternative I can think of besides entering the term as it is in unique_terms(). However, unique_terms return the same value with different capitalization (a big problem for another day).

**Additional context**

**Comment by elijahlowe** [comment]
Here is an example to help illustrate the problem.

Using "TCGA-13-1409" as the id returns results:

```
q = Q('id = "TCGA-13-1409"') # note the double quotes for the string value
r3 = q.run()#table = "gdc-bq-sample.integration", version = "all_v2")
print(r3)

Getting results from database

Total execution time: 1624 ms

        QueryID: beaff3f2-1da3-4099-9dfc-80151baf3727
        Query: SELECT all_v2.* FROM gdc-bq-sample.integration.all_v2 AS all_v2 WHERE (all_v2.id = 'TCGA-13-1409')
        Offset: 0
        Count: 1
        Total Row Count: 1
        GDC Count: 54 
 	PDC Count: 109 
 	IDC Count: 191
        More pages: False
```

While using "tcga-13-1409" as the id returns nothing:

```
q = Q('id = "tcga-13-1409"') # note the double quotes for the string value
r3_1 = q.run()#table = "gdc-bq-sample.integration", version = "all_v2")
print(r3_1)

Getting results from database

Total execution time: 9282 ms

        QueryID: 469e90fe-7d47-4b7b-98f8-90b64c4c118e
        Query: SELECT all_v2.* FROM gdc-bq-sample.integration.all_v2 AS all_v2 WHERE (all_v2.id = 'tcga-13-1409')
        Offset: 0
        Count: 0
        Total Row Count: 0
        GDC Count: 0 
 	PDC Count: 0 
 	IDC Count: 0
        More pages: False
```
        

I found this online about bigquery case sensitivity: https://copycoding.com/d/how-to-do-case-insensitive-compare-in-google-bigquery

**Comment by ACharbonneau** [comment]
Q is case insensitive in release 3.0
