### ISSUE TITLE
Data common version information should print when query is run

### ISSUE THREAD

**Issue by elijahlowe** [CancerDataAggregator/cda-python#88]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When the query is run and the data is printed about the run, that information should include the versioning information for the data commons. See below:
QueryID: 856b6b15-68e2-462e-83e2-0da8c45524eb
Query: SELECT all_v1.* FROM gdc-bq-sample.integration.all_v1 AS all_v1, UNNEST(ResearchSubject) AS _ResearchSubject, UNNEST(_ResearchSubject.identifier) AS _identifier WHERE ((_ResearchSubject.primary_disease_type = 'Ovarian Serous Cystadenocarcinoma') AND (_identifier.system = 'PDC'))
Offset: 0
Count: 100
Total Row Count: 283
More pages: True
**GDC extraction date - 09/27/2021, GDC data release - v30.0
PDC extraction date - 09/27/2021, PDC data release - v2.1
IDC extraction date - 09/27/2021, IDC data release - Version 3.0**

**Describe alternatives you've considered**
The alternative is to run a code snippet using Q.sql. Or an alternative that could be implemented is to call a version function that prints out the release information.

**Additional context**

**Comment by ACharbonneau** [comment]
Let's talk about what we need to do to make this happen in the next release

**Comment by ACharbonneau** [comment]
this didn't get chosen for this round. closing and putting in backlog
