### ISSUE TITLE
Table to query in SQL is unclear/misleading

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#91]
**Description**
The documentation is unclear about what table(s) can be queried via SQL.
The example given is probably misleading. It refers to gdc-bq-sample.cda_mvp.v1
For CDA release 1 the table being queried was gdc-bq-sample.cda_mvp.v3

The sql shown for queries submitted via Q() shows queries against gdc-bq-sample.integration.all_v2. Is that the right table to use for Release 2

**To Reproduce**
See https://cda.readthedocs.io/en/latest/usage.html#q-sql

**Expected behavior**
Clear indication of the table(s) that can be queried. In reality the schema is needed, but in fact that is essentially available through columns(). So all that its likely needed is the table name in which those columns exist.

**Comment by ianfore** [comment]
Validated that gdc-bq-sample.integration.all_v2 gives results consistent with the new schema. 

Having the examples use the current schema would be helpful.

**Comment by ACharbonneau** [comment]
Users can only query the production table, and this is not a settable field.
