### ISSUE TITLE
Query on Subject level File attributes fails

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#92]
**Describe the bug**
When combined with an unnest, queries which specify an attribute of File at the top (Subject) level fail with an "ambiguous column name" error.

**To Reproduce**
```
q1 = Q('ResearchSubject.primary_disease_type = "Ovarian Serous Cystadenocarcinoma"')
q2 = Q('File.data_category = "Imaging"')
q = q1.And(q2)
r = q.run()
print(r)
```

Gives
```
ERROR:root:
            Http Status: 500
            Error Message: Column name File is ambiguous at [1:118]
            
Total execution time: 680 ms
None
```

**Expected behavior**
The query should recognize File.data_category as an attribute of the top (Subect) level File.
The same should apply for all attributes of top level File as follows
```
 'File.id',
 'File.identifier',
 'File.identifier.system',
 'File.identifier.value',
 'File.label',
 'File.data_category',
 'File.data_type',
 'File.file_format',
 'File.associated_project',
 'File.drs_uri',
 'File.byte_size',
 'File.checksum'
```

**Additional context**
Note the following query does not fail. In this case only attributes from the top level File are queried. This suggests the error only occurs when an unnest is present and the unnested object has a File field. There is likely an error in the way the SQL is constructed.
```
q1 = Q('File.data_type = "CT"')
q2 = Q('File.associated_project = "tcga_ov"')
q = q1.And(q2)
r = q.run()
print(r)
```

**Comment by druth314** [comment]
This sounds like it could relate to issue #89 . The solution implemented could be used to fix this solution as well since they both are to be fixing an ambiguous field due to unnesting.

**Comment by ACharbonneau** [comment]
This has been fixed in release 3 (coming out end of June)
