### ISSUE TITLE
Query with = on subject_associated_project fails

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#94]
**Description**
Going by the [usage documentation](https://cda.readthedocs.io/en/latest/usage.html#)  'subject_associated_project = "TCGA-OV" seems like a legitimate query. However, it gives an error. 

This field turns out to be an array of strings (though the [schema](https://cda.readthedocs.io/en/latest/Schema.html) does not indicate this)
``` 
    "subject_associated_project": [
       "TCGA-OV",
        "CPTAC-TCGA",
        "CPTAC-TCGA",
        "tcga_ov"
    ]
```
Arrays of other objects work fine when queried by Q() - so this seems like a bug.

**To Reproduce**
```
q1 = Q('subject_associated_project = "TCGA-OV"')
r = q1.run()
print(r)
```
returns
```
ERROR:root:
            Http Status: 500
            Error Message: No matching signature for operator = for argument types: ARRAY<STRING>, STRING. Supported signature: ANY = ANY at [1:72]
            
Total execution time: 880 ms
```

**Expected behavior**
The query would return any subject where any element of subject_associated_project matched the provided value.

**Comment by elijahlowe** [comment]
Hi @ianfore if you look at the **warning** under the `unique_terms()` section, just above the `Q()` section [here](https://cda.readthedocs.io/en/latest/usage.html#q), it lists several terms that are array type and you cannot use these terms to query, with "subject_associated_project" being one of the terms listed.

**Comment by ianfore** [comment]
Thanks for the note Elijah. That certainly provides the warning - but I would come back to the basic point that one can query on arrays of other kinds of objects, and that there is user benefit to be able to do so for this subject_associated_project. I'll try and provide examples by way of illustration.

In the meantime there are a couple of issues with the 'warning'. I started by detailing them here, but it turned out to be better to create a separate issue.

**Comment by druth314** [comment]
It looks like there are just some issues with that particular fields data type in BigQuery. Any other list type object is a repeated record, and automatically unnested within the Q query translator. Since subject_associated_project is a repeated string type, that needs to be queried slightly differently. For instance the query below is what you are hoping to achieve if you want any patients that are associated with the TCGA-OV project:
SELECT * FROM `gdc-bq-sample.integration.all_v2` where 'TCGA-OV' in unnest(subject_associated_project)

**Comment by ianfore** [comment]
Indeed. SQL to the rescue yet again. 

This is another case which adds complexity to what the Q query translator has to do. As more and more is done - is this just writing a query language. See [cda-python/issues/15](https://github.com/CancerDataAggregator/cda-python/issues/15).

**Comment by ACharbonneau** [comment]
This has been fixed in release 3 (coming out end of June)
