### ISSUE TITLE
Warning for unique terms is inaccurate

### ISSUE THREAD

**Issue by ianfore** [CancerDataAggregator/cda-python#96]
**Description**
See the warnings [here](https://cda.readthedocs.io/en/latest/usage.html#unique-terms).

1. It says "Below is the list of column values that do have unique_terms"
This seems to be the list of fields for which unique_terms are not provided. If so a 'not' is missing
2. The example given is not accurate, it confuses Arrays and complex datatypes
It is not that File.identifier is comprised of system and value that makes it an Array containing multiple values. 'identifier' is a complex datatype consisting of system and value. The file.identifier field is a Array of identifiers.
3. ResearchSubject.Specimen.File.associated_project does actually respond to unique_terms() and should not be in the list

**To Reproduce**
1 & 2 see the warning at the link above
3. unique_terms('ResearchSubject.Specimen.File.associated_project')

**Comment by elijahlowe** [comment]
Thanks for the catch @ianfore. I've updated the warning appropriately

**Comment by elijahlowe** [comment]
@ianfore thanks for clearing that up, I understand the confusion now. I should have said **nested array** datatypes. You cannot search on the top level and will have to search using one of the lower levels. For example, you can not search on File.identifier but you can search on File.identifier.system and File.identifier.value. See the example json below:

{'File': [{'label': '0012f466-075a-4d47-b1d7-e8e63e8b9c99.vep.vcf.gz',
  'associated_project': ['TCGA-BRCA'],
  'drs_uri': 'drs://dg.4DFC:0012f466-075a-4d47-b1d7-e8e63e8b9c99',
  **'identifier': [{'system': 'GDC', 'value': '0012f466-075a-4d47-b1d7-e8e63e8b9c99'}]**
  ...

So, the warning message requires a small modification, so it's not completely inaccurate. "ResearchSubject.Specimen.File.associated_project" is not the top level of the nested Array, "ResearchSubject", "ResearchSubject.Specimen", and "ResearchSubject.Specimen.File" would each be the top levels of their nested array.
